import type { Metadata } from "next";
import "./globals.css";
import "./mediaquery.css";
import { Poppins } from "next/font/google"
import "bootstrap-icons/font/bootstrap-icons.css";
// import "bootstrap/dist/css/bootstrap.min.css";
import toast, { Toaster } from "react-hot-toast";
import Provider from "@/provider";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Bellyto.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>{children}</Provider>
        <Toaster
          position="top-center"
          toastOptions={{
            className: "toast",
            duration: 5000,
            removeDelay: 1000,
          }}
        />
      </body>
    </html>
  );
}
